import type { Metadata } from "next";

import "@/styles/globals.css";

import { cn } from "@/lib/utils";
import { geistSans } from "@/lib/fonts";

import { ThemeProvider } from "@/components/providers/theme-provider";

import { PropsWithChildren } from "@/common/types/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
  return (
    <html lang="en">
      <body className={cn("font-geist", geistSans.variable)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
